name: Add issues to Jozu planning project

on:
  issues:    
    types: 
        - opened
       
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e   ## v1.11.6
        with:
          app-id: ${{ vars.JOZU_PILOT_ID }}
          private-key: ${{ secrets.JOZU_PILOT_PRIVATE_KEY}}
          owner: jozu-ai

      - name: Add To GitHub projects
        uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e  ## v1.0.2
        with:
          project-url: https://github.com/orgs/jozu-ai/projects/1
          github-token: ${{ steps.generate-token.outputs.token }}
