name: PR Builds

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # 5.5.0
        with:
          python-version: "3.13"
          cache: poetry
      
      - name: Install dependencies
        run: |
          poetry install --with=dev
  
      - name: Run Tests
        run: poetry run pytest
      
      - name: Run Ruff checker
        run: poetry run ruff check